services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ${FILEPATH}:/app/data
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis 

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data: